package com.ronsong.mtgjsonapi.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import java.util.List;

@Data
@JsonIgnoreProperties(ignoreUnknown=true)
public class CardSet {
    private String artist;
    private List<String> artistIds;
    private String asciiName;
    private List<String> attractionLights;
    private List<String> availability;
    private List<String> boosterTypes;
    private String borderColor;
    private List<String> cardParts;
    private List<String> colorIdentity;
    private List<String> colorIndicator;
    private List<String> colors;
    private Integer convertedManaCost;
    private String defense;
    private String duelDeck;
    private Integer edhrecRank;
    private Integer edhrecSaltiness;
    private Integer faceConvertedManaCost;
    private String faceFlavorName;
    private Integer faceManaValue;
    private String faceName;
    private List<String> finishes;
    private String flavorName;
    private String flavorText;
    //    foreignData?: ForeignData[];
    private List<String> frameEffects;
    private String frameVersion;
    private String hand;
    private Boolean hasAlternativeDeckLimit;
    private Boolean hasContentWarning;
    private Boolean hasFoil;
    private Boolean hasNonFoil;
    //    identifiers: Identifiers;
    private Boolean isAlternative;
    private Boolean isFullArt;
    private Boolean isFunny;
    private Boolean isOnlineOnly;
    private Boolean isOversized;
    private Boolean isPromo;
    private Boolean isRebalanced;
    private Boolean isReprint;
    private Boolean isReserved;
    private Boolean isStarter;
    private Boolean isStorySpotlight;
    private Boolean isTextless;
    private Boolean isTimeshifted;
    private List<String> keywords;
    private String language;
    private String layout;
    // private LeadershipSkills leadershipSkills;
    // private Legalities legalities;
    private String life;
    private String loyalty;
    private String manaCost;
    private Integer manaValue;
    private String name;
    private String number;
    private List<String> originalPrintings;
    private String originalReleaseDate;
    private String originalText;
    private String originalType;
    private List<String> otherFaceIds;
    private String power;
    private List<String> printings;
    private List<String> promoTypes;
    // private PurchaseUrls purchaseUrls;
    private String rarity;
    // private RelatedCards relatedCards;
    private List<String> rebalancedPrintings;
    // List<Rulings> rulings;
    private String securityStamp;
    private String setCode;
    private String side;
    private String signature;
    // private List<String> sourceProducts;
    private List<String> subsets;
    private List<String> subtypes;
    private List<String> supertypes;
    private String text;
    private String toughness;
    private String type;
    private List<String> types;
    private String uuid;
    private List<String> variations;
    private String watermark;
}
